Draft API specification.
aperture-data/aperturedb-python pull request #44
Opened 2022-02-28 17:42 UTC by gsaluja9

**Starting to implement an Object mapper API.**
It would enable the users to interact with athena using an API that alleviates the need to be familiar with the [native API](https://docs.aperturedata.io/index.html).

It is going to be designed on the guidelines of a similar ORM library, for example [SQL Alchemy](https://www.sqlalchemy.org/) or [Django's ORM](https://docs.djangoproject.com/en/4.0/topics/db/queries/).

The following are some considerations for implementing it this time:
- It will support CRUD operations for the object types covered by the native API.
- It will treat the Entities in a more or less common way, and implement the basic DB operations (rather than the prescribed ways of actions on these objects.
- The main goal is will be to add simplicity and intuitiveness for interacting with VDMS.

2022-03-04 17:49 UTC, luisremis requested changes
This is going in the right direction. Before reviewing any implementation details, it would be nice to have a more complete description of the API, where most of the discussion will go.

2022-03-04 17:49 UTC, luisremis commented on .gitignore
> +test/input/blobs/*
```suggestion
test/input/blobs/*

```

2022-03-04 17:49 UTC, luisremis commented on README.md
> +This API allows the user to interact with the database with the idea of objects that can be Created, Read, Updated and Deleted through an intutive interface involving these objects.
```suggestion
This API allows the user to interact with the database with the idea of objects that can be 
Created, Read, Updated and Deleted through an intuitive interface involving these objects.
```

2022-03-04 17:49 UTC, luisremis commented on README.md
> +| Object | Dcumentation |
```suggestion
| Object | Documentation |
```

2022-03-04 17:49 UTC, luisremis commented on README.md
> +**Create an Image**
this is a great start, but what we would like is two separate sets of documentation: 
1) docstrings or similar, to let users understand the API. Ideally, we would like to generate an html documentation (like this: https://pytorch.org/docs/stable/torch.html (which actually uses read-the-docs))
2) Example documentation, for users to see some use-cases. For the examples, you can consider using read-the-docs/sphinx as we are using for documentation ApertureDB API

2022-03-04 17:49 UTC, luisremis commented on README.md
> +    img_data = instream.read()
where is img_data used?

2022-03-04 17:49 UTC, luisremis commented on README.md
> +bbox = bboxes.get(id=34)
this is a good start. Are there other, more friendly, ways of interacting with the objects without having to specify ids? I would try to come up with something higher level than that.

2022-03-04 17:49 UTC, luisremis commented on aperturedb/BoundingBoxes.py
> +        self._object_type = "BoundingBox"
```suggestion
        self._object_type = "BoundingBox"

```

2022-03-04 17:49 UTC, luisremis commented on test/test_Image.py
> +    unittest.main()
```suggestion
    unittest.main()

```

2022-03-04 17:49 UTC, luisremis commented on test/utils.py
> +        bbox.delete()
```suggestion
        bbox.delete()

```

2022-03-04 17:49 UTC, luisremis commented on test/utils.py
> +def cleanDB(db):
scary name for a method.

2022-03-30 14:34 UTC, closed without merging

2022-03-30 14:34 UTC, gsaluja9 commented
done in another.